# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170128_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='entry',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
