# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='created_by',
            new_name='owner',
        ),
    ]
