# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170202_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='owner',
            new_name='employer',
        ),
    ]
