# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170203_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_employee',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
