# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_auto_20170128_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Entry')),
            ],
        ),
    ]
