# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0003_auto_20170218_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='dk_event_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
