# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0004_auto_20170218_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='dk_event_url',
            new_name='url',
        ),
    ]
